api_platform:
    title: 'API todo'
    description: 'Ma jolie API avec API Platform'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
