<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZzahhk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZzahhk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZzahhk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZzahhk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMZzahhk\App_KernelDevDebugContainer([
    'container.build_hash' => 'MZzahhk',
    'container.build_id' => '45dfa8b4',
    'container.build_time' => 1670318727,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZzahhk');
