<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9y1CJGR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9y1CJGR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9y1CJGR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9y1CJGR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9y1CJGR\App_KernelDevDebugContainer([
    'container.build_hash' => '9y1CJGR',
    'container.build_id' => '4894e297',
    'container.build_time' => 1670321909,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9y1CJGR');
