<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBgOcUXx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBgOcUXx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBgOcUXx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBgOcUXx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBgOcUXx\App_KernelDevDebugContainer([
    'container.build_hash' => 'BgOcUXx',
    'container.build_id' => 'ec8a876f',
    'container.build_time' => 1670321391,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBgOcUXx');
